### ISSUE TITLE
[BUG] LungingEventArgs doesn't get called

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1734]
Reported by @ITeMbI4 in https://discord.com/channels/656673194693885975/1064138679171428373/1064138679171428373

**Comment by ITeMbI4** [comment]
Should be fixed in https://github.com/Exiled-Team/EXILED/pull/1709
But need testing

**Comment by joker-119** [comment]
The above fix is not a valid "fix" for this bug, as it doesn't fix the event, instead it adds a new, different event, that is fired at a different time with different arguments.

#1790 is therefore not a bugfix, but a new feature.

**Comment by VALERA771** [comment]
I couldn't find other methods that call before lunge so this is the only way I could "fix" it
