### ISSUE TITLE
[BUG] CustomItem.Give doesn't work as intended

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1748]
**Describe the bug**
``CustomItem.Give(player, false)`` should give the specified player the item while not displaying a message.

**To Reproduce**
![image](https://user-images.githubusercontent.com/45165615/233547238-41251b37-6cb6-4c16-9f64-71b0f7f0bb96.png)

**Expected behavior**
There shouldn't be a message.

Reported by: @TtroubleTT

**Comment by TtroubleTT** [comment]
To note in order to be able to reproduce the item that you give in CustomItem.Give() you have to make sure its from only the custom item class and not custom weapon as for some reason it works if its a custom weapon.

**Comment by joker-119** [comment]
Pretty sure this was fixed in 6.1 aswell

**Comment by Misaka-ZeroTwo** [comment]
> Pretty sure this was fixed in 6.1 aswell

According trouble, https://discord.com/channels/656673194693885975/1077347288244047874/1098831660541280308, still appearing.

**Comment by Misaka-ZeroTwo** [comment]
![image](https://user-images.githubusercontent.com/45165615/233712605-c504967a-a4fe-4367-88fb-7cc554868d2f.png)

![image](https://user-images.githubusercontent.com/45165615/233712561-11c0cee0-82dd-47c8-bc77-765f356a042b.png)

ShowPickedUpMessage is called twice
